services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${FACE_TRACK__PG_USER}
      POSTGRES_PASSWORD: ${FACE_TRACK__PG_PASS}
      POSTGRES_DB: ${FACE_TRACK__PG_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${FACE_TRACK__PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4221:4221"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: